# Part C

# Dockerfile for Challenge B
# This Docker container is designed to execute the program from Challenge B.
# It reads the output generated by Challenge A as input, processes the data,
# and saves the resulting output in a file that is accessible to the Docker host.
# The container ensures the necessary files are copied, compiled, executed, and
# the output is exposed for further use.


# Use OpenJDK 17 as the base image with a slim profile to keep the image size minimal
FROM openjdk:17-jdk-slim

# Set the working directory inside the container to /app
WORKDIR /app

# Copy the Java source file and input data file into the container
COPY src/PartB.java /app/
COPY random_data_objects.txt /app/

# Compile the Java file inside the container to generate the class file
RUN javac PartB.java

# Run the compiled Java program and ensure the container exits after execution
CMD ["java", "PartB"]
